# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: python:2.7-slim
    steps:
      - checkout
      - run: mkdir test-results
      # Download and cache dependencies
      - run:
          name: install dependencies
          command: |
            pip install --trusted-host pypi.python.org -r requirements.txt

      # run tests
      - run:
          name: run tests
          command: |
            python tests.py
      - store_test_results:
          path: test-results

workflows:
  version: 2
  two_job_flow:
    jobs:
      - test

